#
# prometheus.yml
#
# A simple Prometheus configuration for connecting a Prometheus
# instance with the Prometheus exporter that comes as part of
# synse-graphql.
#

scrape_configs:
  - job_name: 'synse'

    static_configs:
      - targets: ['synse-graphql:5050']
