#
# monitoring.yml
#
# This compose file combines all of the components described in the
# "Monitoring your physical infrastructure with Synse" tutorial. It
# is provided as a convenient way to stand up the tutorial without
# having to manually go through each of the steps.
#
# This uses compose file format version 3.0, compatible with docker
# engine release version 1.13.0+
#

version: "3"
services:

  # Synse Server w/ emulator plugin
  synse-server:
    container_name: synse_server
    image: vaporio/synse-server
    command: enable-emulator
    ports:
      - 5000:5000


  # Synse GraphQL
  # TODO -- config for synse-server -- I believe it should pick up synse-server
  # via the default config, but it would be good to show an example of how to
  # configure for non-default configs..
  synse-graphql:
    container_name: synse_graphql
    image: vaporio/synse-graphql
    ports:
      - 5001:5001
    links:
      - synse-server

  # Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    links:
      - synse-graphql

  # Grafana Dashboard
  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    links:
      - prometheus